import type { Metadata } from "next";
import "./globals.css";
import RecoilRootProvider from "@/util/recoilRootProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilRootProvider>
      <html lang="en">
        <body className="flex flex-col w-full h-full justify-center">
          {children}
        </body>
      </html>
    </RecoilRootProvider>
  );
}
